package io.smithy.unison.codegen.generators;

import io.smithy.unison.codegen.UnisonWriter;

/**
 * Generates Unison functions for XML encoding and decoding.
 * 
 * <p>Used by the REST-XML protocol (S3, CloudFront, Route 53, SES) for
 * serializing request bodies and deserializing response bodies.
 * 
 * <h2>Generated Functions</h2>
 * <ul>
 *   <li>{@code aws.xml.extractElement} - Extract text content from XML element</li>
 *   <li>{@code aws.xml.extractAttribute} - Extract attribute value from XML element</li>
 * </ul>
 * 
 * <p>Note: Generic encode/decode functions are not generated. Each structure type
 * has its own type-specific serialization and parsing functions generated by the
 * protocol generators.
 * 
 * <h2>XML Format</h2>
 * <p>AWS REST-XML uses a specific XML format:
 * <pre>
 * &lt;RootElement xmlns="http://s3.amazonaws.com/doc/2006-03-01/"&gt;
 *   &lt;ChildElement&gt;value&lt;/ChildElement&gt;
 *   &lt;NestedElement&gt;
 *     &lt;Field&gt;value&lt;/Field&gt;
 *   &lt;/NestedElement&gt;
 * &lt;/RootElement&gt;
 * </pre>
 */
public class XmlGenerator {
    
    /**
     * Creates a new XmlGenerator.
     */
    public XmlGenerator() {
    }
    
    /**
     * Generates all XML utility functions.
     * 
     * @param writer The Unison code writer
     */
    public void generate(UnisonWriter writer) {
        generateXmlEscape(writer);
        generateExtractElement(writer);
        generateExtractAttribute(writer);
    }
    
    /**
     * Generates the XML escape function for special characters.
     */
    public void generateXmlEscape(UnisonWriter writer) {
        writer.writeDocComment(
            "Escape special XML characters in text content.\n\n" +
            "Converts: & -> &amp; < -> &lt; > -> &gt; \" -> &quot; ' -> &apos;");
        
        writer.writeSignature("aws.xml.escape", "Text -> Text");
        writer.write("aws.xml.escape text =");
        writer.indent();
        writer.write("text");
        writer.indent();
        writer.writeWithNoFormatting("|> Text.replace \"&\" \"&amp;\"");
        writer.writeWithNoFormatting("|> Text.replace \"<\" \"&lt;\"");
        writer.writeWithNoFormatting("|> Text.replace \">\" \"&gt;\"");
        writer.writeWithNoFormatting("|> Text.replace \"\\\"\" \"&quot;\"");
        writer.writeWithNoFormatting("|> Text.replace \"'\" \"&apos;\"");
        writer.dedent();
        writer.dedent();
        writer.writeBlankLine();
    }
    
    /**
     * Generates the XML unescape function.
     */
    public void generateXmlUnescape(UnisonWriter writer) {
        writer.writeDocComment(
            "Unescape XML entities in text content.\n\n" +
            "Converts: &amp; -> & &lt; -> < &gt; -> > &quot; -> \" &apos; -> '");
        
        writer.writeSignature("aws.xml.unescape", "Text -> Text");
        writer.write("aws.xml.unescape text =");
        writer.indent();
        writer.write("text");
        writer.indent();
        writer.writeWithNoFormatting("|> Text.replace \"&amp;\" \"&\"");
        writer.writeWithNoFormatting("|> Text.replace \"&lt;\" \"<\"");
        writer.writeWithNoFormatting("|> Text.replace \"&gt;\" \">\"");
        writer.writeWithNoFormatting("|> Text.replace \"&quot;\" \"\\\"\"");
        writer.writeWithNoFormatting("|> Text.replace \"&apos;\" \"'\"");
        writer.dedent();
        writer.dedent();
        writer.writeBlankLine();
    }
    
    /**
     * Generates the XML element extraction function.
     * 
     * <p>Extracts the text content of a named XML element:
     * <pre>
     * extractElement "Code" "&lt;Error&gt;&lt;Code&gt;NoSuchKey&lt;/Code&gt;&lt;/Error&gt;"
     * -- Returns: "NoSuchKey"
     * </pre>
     */
    public void generateExtractElement(UnisonWriter writer) {
        writer.writeDocComment(
            "Extract text content from an XML element by tag name.\n\n" +
            "Example: extractElement \"Code\" \"<Error><Code>NoSuchKey</Code></Error>\"\n" +
            "Returns: \"NoSuchKey\"\n\n" +
            "Returns empty string if element not found.");
        
        writer.writeSignature("aws.xml.extractElement", "Text -> Text -> Text");
        writer.write("aws.xml.extractElement tagName xml =");
        writer.indent();
        writer.write("let");
        writer.indent();
        writer.writeWithNoFormatting("openTag = \"<\" ++ tagName ++ \">\"");
        writer.writeWithNoFormatting("closeTag = \"</\" ++ tagName ++ \">\"");
        writer.write("startIdx = Text.indexOf openTag xml");
        writer.write("endIdx = Text.indexOf closeTag xml");
        writer.dedent();
        writer.write("match (startIdx, endIdx) with");
        writer.indent();
        writer.write("(Some start, Some end) ->");
        writer.indent();
        writer.write("contentStart = start + Text.size openTag");
        writer.write("Text.slice contentStart end xml |> aws.xml.unescape");
        writer.dedent();
        writer.write("_ -> \"\"");
        writer.dedent();
        writer.dedent();
        writer.writeBlankLine();
    }
    
    /**
     * Generates the XML attribute extraction function.
     */
    public void generateExtractAttribute(UnisonWriter writer) {
        writer.writeDocComment(
            "Extract an attribute value from an XML element.\n\n" +
            "Example: extractAttribute \"xmlns\" \"<Bucket xmlns=\\\"http://...\\\">...</Bucket>\"\n" +
            "Returns: \"http://...\"\n\n" +
            "Returns empty string if attribute not found.");
        
        writer.writeSignature("aws.xml.extractAttribute", "Text -> Text -> Text");
        writer.write("aws.xml.extractAttribute attrName xml =");
        writer.indent();
        writer.write("let");
        writer.indent();
        writer.writeWithNoFormatting("pattern = attrName ++ \"=\\\"\"");
        writer.write("startIdx = Text.indexOf pattern xml");
        writer.dedent();
        writer.write("match startIdx with");
        writer.indent();
        writer.write("Some start ->");
        writer.indent();
        writer.write("valueStart = start + Text.size pattern");
        writer.writeWithNoFormatting("rest = Text.drop valueStart xml");
        writer.writeWithNoFormatting("endIdx = Text.indexOf \"\\\"\" rest");
        writer.write("match endIdx with");
        writer.indent();
        writer.write("Some end -> Text.take end rest");
        writer.write("None -> \"\"");
        writer.dedent();
        writer.dedent();
        writer.write("None -> \"\"");
        writer.dedent();
        writer.dedent();
        writer.writeBlankLine();
    }
    
    /**
     * Generates a helper to wrap content in an XML element.
     */
    public void generateElement(UnisonWriter writer) {
        writer.writeDocComment(
            "Wrap content in an XML element.\n\n" +
            "Example: element \"Name\" \"MyBucket\" -> \"<Name>MyBucket</Name>\"");
        
        writer.writeSignature("aws.xml.element", "Text -> Text -> Text");
        writer.write("aws.xml.element tagName content =");
        writer.indent();
        writer.writeWithNoFormatting("\"<\" ++ tagName ++ \">\" ++ aws.xml.escape content ++ \"</\" ++ tagName ++ \">\"");
        writer.dedent();
        writer.writeBlankLine();
    }
    
    /**
     * Generates a helper to create an XML element with attributes.
     */
    public void generateElementWithAttrs(UnisonWriter writer) {
        writer.writeDocComment(
            "Create an XML element with attributes.\n\n" +
            "Example: elementWithAttrs \"Bucket\" [(\"xmlns\", \"http://...\")] \"content\"\n" +
            "-> \"<Bucket xmlns=\\\"http://...\\\">content</Bucket>\"");
        
        writer.writeSignature("aws.xml.elementWithAttrs", "Text -> [(Text, Text)] -> Text -> Text");
        writer.write("aws.xml.elementWithAttrs tagName attrs content =");
        writer.indent();
        writer.write("let");
        writer.indent();
        writer.write("attrStr = attrs");
        writer.indent();
        writer.writeWithNoFormatting("|> List.map (cases (name, value) -> \" \" ++ name ++ \"=\\\"\" ++ value ++ \"\\\"\")");
        writer.writeWithNoFormatting("|> Text.join \"\"");
        writer.dedent();
        writer.dedent();
        writer.writeWithNoFormatting("\"<\" ++ tagName ++ attrStr ++ \">\" ++ content ++ \"</\" ++ tagName ++ \">\"");
        writer.dedent();
        writer.writeBlankLine();
    }
    
    /**
     * Generates a helper to create an optional XML element.
     */
    public void generateOptionalElement(UnisonWriter writer) {
        writer.writeDocComment(
            "Create an XML element only if the value is present.\n\n" +
            "Example: optionalElement \"VersionId\" (Some \"v1\") -> \"<VersionId>v1</VersionId>\"\n" +
            "Example: optionalElement \"VersionId\" None -> \"\"");
        
        writer.writeSignature("aws.xml.optionalElement", "Text -> Optional Text -> Text");
        writer.write("aws.xml.optionalElement tagName maybeValue =");
        writer.indent();
        writer.write("match maybeValue with");
        writer.indent();
        writer.write("Some value -> aws.xml.element tagName value");
        writer.write("None -> \"\"");
        writer.dedent();
        writer.dedent();
        writer.writeBlankLine();
    }
    
    /**
     * Generates all XML functions including helpers.
     * 
     * @param writer The Unison code writer
     */
    public void generateAll(UnisonWriter writer) {
        writer.writeComment("=== AWS XML Utilities ===");
        writer.writeBlankLine();
        
        generateXmlEscape(writer);
        generateXmlUnescape(writer);
        generateElement(writer);
        generateElementWithAttrs(writer);
        generateOptionalElement(writer);
        generateExtractElement(writer);
        generateExtractAttribute(writer);
        
    }
}
